/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import DAO.Affichage;
import DAO.Bd;
import DAO.SouscriptionDAO;
import static DAO.SouscriptionDAO.getIdAbonneByNom;
import static DAO.SouscriptionDAO.getIdAbonnementByLibelle;
import static DAO.SouscriptionDAO.souscrireAbonnement;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author AN
 */

public class Souscription extends javax.swing.JPanel {

    /**
     * Creates new form Souscription
     */
    public Souscription() {
        initComponents();
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        // Récupérer les données de la base de données
        List<Object[]> nom_pre = Affichage.getAbonnes();
        for (Object[] np : nom_pre) {
            table.addRow(np);
        }
    }
    public Souscription(String ancienLibelle, String duree, double prix) {
        initComponents();
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

        // Remplir les champs avec les informations de l'abonnement sélectionné
        /*txtLibelle.setText(ancienLibelle);
        txtDuree.setText(duree);
        txtPrix.setText(String.valueOf(prix));*/

        // Récupérer les abonnés de la base de données et remplir la table
        //DefaultTableModel model = (DefaultTableModel) table.getModel();
        List<Object[]> nom_pre = Affichage.getAbonnes();
        for (Object[] np : nom_pre) {
            table.addRow(np);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jButtonSous = new javax.swing.JButton();
        jButtonAnul = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Liste des Abonnés");

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        jButtonSous.setBackground(new java.awt.Color(255, 204, 51));
        jButtonSous.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonSous.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSous.setText("Souscrir");
        jButtonSous.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSousActionPerformed(evt);
            }
        });

        jButtonAnul.setBackground(new java.awt.Color(255, 51, 0));
        jButtonAnul.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonAnul.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnul.setText("Annuler");
        jButtonAnul.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnul, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSous, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnul, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSous, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
   
     
    private void jButtonSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSousActionPerformed
        // TODO add your handling code here:
        // Récupérer la ligne sélectionnée dans le tableau
    int selectedRow = table.getSelectedRow();
    if (selectedRow >= 0) {
        // Récupérer les informations depuis les colonnes du tableau
        String nomAbonne = (String) table.getValueAt(selectedRow, 0);  // Nom de l'abonné
        String libelleAbonnement = (String) table.getValueAt(selectedRow, 0);  // Libellé de l'abonnement
        
        // Récupérer les ID à partir de la base de données avec la jointure
        int idAbonne = getIdAbonneByNom(nomAbonne);  // Méthode pour obtenir l'ID de l'abonné
        int idAbonnement = getIdAbonnementByLibelle(libelleAbonnement);  // Méthode pour obtenir l'ID de l'abonnement
        System.out.println(idAbonne);
        System.out.println(idAbonnement);
        if (idAbonne != -1 && idAbonnement != -1) {
            // Appeler la méthode DAO pour souscrire l'abonnement
            boolean isUpdated = SouscriptionDAO.souscrireAbonnement(idAbonne, idAbonnement);
            
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Souscription ajoutée avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                // Rafraîchir la table ou autre action nécessaire après l'ajout
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la souscription de l'abonnement.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erreur : ID de l'abonné ou de l'abonnement introuvable.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne d'abonnement.", "Aucune sélection", JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_jButtonSousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnul;
    private javax.swing.JButton jButtonSous;
    private javax.swing.JLabel jLabel1;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
