/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import DAO.Affichage;
import static DAO.CgAbonne.supprimerAbonne;
import static DAO.CgAbonnement.supprimerAbonnement;
import DAO.SouscriptionDAO;
import com.raven.model.Model_Card;
import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.awt.Frame;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gerùain
 */
public class TAbonnement extends javax.swing.JPanel {

    /**
     * Creates new form TAbonnement
     */
    public TAbonnement() {
        initComponents();
        int total_abonne = 0;
        int total_profit = 0;
        int abonne_viral = 0;

        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        // Récupérer les données de la base de données
        List<Object[]> abonnements = Affichage.getAbonnement();
        for (Object[] abonnement : abonnements) {
            table.addRow(abonnement);
            total_abonne = total_abonne + 1;
            // Ajouter le prix mensuel de l'abonnement à total_profit
            double prixMensuel = (double) abonnement[2]; // Récupération du prix depuis l'Object[]
            total_profit += prixMensuel;

        }
        card1.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/stock.png")), "Total Abonnement", Integer.toString(total_abonne), "Tous les Abonnement publier dans le mois"));
        card2.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/profit.png")), "TotalProfit", Integer.toString(total_profit), "Increased by NokeGym"));
        card3.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/flag.png")), "Abonnement viral", Integer.toString(abonne_viral), "xixoxixo"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        card1 = new com.raven.component.Card();
        card2 = new com.raven.component.Card();
        card3 = new com.raven.component.Card();
        jPanel1 = new javax.swing.JPanel();
        jButtonMod = new javax.swing.JButton();
        jButtonSupp = new javax.swing.JButton();
        jButtonSous = new javax.swing.JButton();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();

        panel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        card1.setColor1(new java.awt.Color(142, 142, 250));
        card1.setColor2(new java.awt.Color(123, 123, 245));
        panel.add(card1);

        card2.setColor1(new java.awt.Color(186, 123, 247));
        card2.setColor2(new java.awt.Color(167, 94, 236));
        panel.add(card2);

        card3.setColor1(new java.awt.Color(241, 208, 62));
        card3.setColor2(new java.awt.Color(211, 184, 61));
        panel.add(card3);

        jButtonMod.setBackground(new java.awt.Color(0, 0, 255));
        jButtonMod.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonMod.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMod.setText("Modifier");
        jButtonMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonSupp.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSupp.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonSupp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupp.setText("Supprimer");
        jButtonSupp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppActionPerformed(evt);
            }
        });

        jButtonSous.setBackground(new java.awt.Color(255, 204, 51));
        jButtonSous.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonSous.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSous.setText("Souscrit à un abonné");
        jButtonSous.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSous, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSous, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel.add(jPanel1);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Liste des Abonnements");

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libéllé", "Durée", "Prix/mois"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(612, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 445, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            // Récupérer les valeurs actuelles
            String ancienLibelle = (String) table.getValueAt(selectedRow, 0);

            // Correction de la récupération de la durée
            Object dureeObj = table.getValueAt(selectedRow, 1);
            String duree = String.valueOf(dureeObj);

            // Correction de la récupération du prix
            Object prixObj = table.getValueAt(selectedRow, 2);
            double prix;
            if (prixObj instanceof Number) {
                prix = ((Number) prixObj).doubleValue();
            } else {
                prix = Double.parseDouble(prixObj.toString()); // Conversion en double si nécessaire
            }

            // Ouvrir la fenêtre de modification
            ModifAbonnement modifAbonnement = new ModifAbonnement(ancienLibelle, duree, prix);

            JDialog dialog = new JDialog();
            dialog.setTitle("Modifier Abonnement");
            dialog.setModal(true);
            dialog.setContentPane(modifAbonnement);
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

            // Rafraîchir le tableau après la fermeture
            refreshTable();
            //dialog.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonnement à modifier.", "Aucune sélection", JOptionPane.WARNING_MESSAGE);
        }
        /*/int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            String ancienLibelle = (String) table.getValueAt(selectedRow, 0);

            Object dureeObj = table.getValueAt(selectedRow, 1);
            String duree = String.valueOf(dureeObj);

            Object prixObj = table.getValueAt(selectedRow, 2);
            double prix;
            if (prixObj instanceof Number) {
                prix = ((Number) prixObj).doubleValue();
            } else {
                prix = Double.parseDouble(prixObj.toString());
            }

            // Créer un JDialog pour la modification
            JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Modifier Abonnement", true);

            // Créer le panneau de modification en lui passant le JDialog
            ModifAbonnement modifAbonnement = new ModifAbonnement(dialog, ancienLibelle, duree, prix);

            dialog.setContentPane(modifAbonnement);
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

            // Rafraîchir le tableau après la fermeture du dialogue
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonnement à modifier.", "Aucune sélection", JOptionPane.WARNING_MESSAGE);
        }*/
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            String libelle = (String) table.getValueAt(selectedRow, 0);
            boolean isDeleted = supprimerAbonnement(libelle);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Abonné supprimé avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                refreshTable(); // Rafraîchir le tableau
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression de l'abonnement.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonnement à supprimer.", "Aucun abonné sélectionné", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSuppActionPerformed

    private void jButtonSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSousActionPerformed
// TODO add your handling code here:
        // TODO add your handling code here:
        /*int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
        // Récupérer les valeurs actuelles
        String ancienLibelle = (String) table.getValueAt(selectedRow, 0);
        // Correction de la récupération de la durée
        Object dureeObj = table.getValueAt(selectedRow, 1);
        String duree = String.valueOf(dureeObj);
        // Correction de la récupération du prix
        Object prixObj = table.getValueAt(selectedRow, 2);
        double prix;
        if (prixObj instanceof Number) {
        prix = ((Number) prixObj).doubleValue();
        } else {
        prix = Double.parseDouble(prixObj.toString()); // Conversion en double si nécessaire
        }
        // Ouvrir la fenêtre de souscription
        Souscription souscription = new Souscription(ancienLibelle, duree, prix);
        JDialog dialog = new JDialog();
        dialog.setTitle("souscrivez les abonné");
        dialog.setModal(true);
        dialog.setContentPane(souscription);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        // Rafraîchir le tableau après la fermeture
        refreshTable();
        //dialog.dispose();
        } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonnement à modifier.", "Aucune sélection", JOptionPane.WARNING_MESSAGE);
        }*/
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            // Récupérer les valeurs de la ligne sélectionnée
            String ancienLibelle = (String) table.getValueAt(selectedRow, 0);
            String duree = String.valueOf(table.getValueAt(selectedRow, 1));

            Object prixObj = table.getValueAt(selectedRow, 2);
            double prix = (prixObj instanceof Number) ? ((Number) prixObj).doubleValue() : Double.parseDouble(prixObj.toString());

            // Ouvrir la fenêtre de souscription
            JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Souscription", true);
            Souscription souscription = new Souscription(ancienLibelle, duree, prix);
            dialog.setContentPane(souscription);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Rafraîchir la table après fermeture du JDialog
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonnement à souscrire.", "Aucune sélection", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSousActionPerformed

    private void refreshTable() {
        table.setRowCount(0); // Vider la table
        List<Object[]> abonnements = Affichage.getAbonnement();
        for (Object[] abonnement : abonnements) {
            table.addRow(abonnement);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Card card1;
    private com.raven.component.Card card2;
    private com.raven.component.Card card3;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonSous;
    private javax.swing.JButton jButtonSupp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane panel;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
