/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import DAO.Affichage;
import DAO.CgAbonne;
import static DAO.CgAbonne.supprimerAbonne;
import static DAO.CgStatus.renouvelerAbonnement;
import static DAO.CgStatus.resilierAbonnement;
import com.raven.component.Menu;
import com.raven.main.Ma;
import com.raven.model.Model_Card;
import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Gerùain
 */

public class TAbonne extends javax.swing.JPanel {

    /**
     * Creates new form TAbonne
     */
    public TAbonne() {
        initComponents();
        int total_abonne = 0;
        int total_actif = 0;
        int total_passif = 0;

        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        // Récupérer les données de la base de données
        List<Object[]> abonnes = Affichage.getAbonnes();
        for (Object[] abonne : abonnes) {
            table.addRow(abonne);
            total_abonne++; // Incrémente le nombre total d'abonnés

            StatusType statut = (StatusType) abonne[4]; // Récupération du statut

            if (statut == StatusType.OUI) {
                total_actif++; // Incrémente les abonnés actifs
            } else {
                total_passif++; // Incrémente les abonnés non actifs
            }
        }

        card1.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/abdo.png")), "Total Abonné", Integer.toString(total_abonne), "Stastistic du moi Dernier"));
        card2.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/actif.png")), "Abonné Actif", Integer.toString(total_actif), "Dans ce mois si"));
        card3.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/croix.png")), "Abonné non Actif", Integer.toString(total_passif), "Dans ce mois si"));
        //table.addRow(new Object[]{"Mike Bhand", "mikebhand@gmail.com", "Admin", "25 Apr,2018", StatusType.NON});
        //table.addRow(new Object[]{"Andrew Strauss", "andrewstrauss@gmail.com", "Editor", "25 Apr,2018", StatusType.OUI});

    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#6BFF69"), 0, getHeight(), Color.decode("#6BFF69"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.setColor(new Color(255, 255, 255, 50));
        g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
        g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        card1 = new com.raven.component.Card();
        card2 = new com.raven.component.Card();
        card3 = new com.raven.component.Card();
        jPanel1 = new javax.swing.JPanel();
        jButtonMod = new javax.swing.JButton();
        jButtonSupp = new javax.swing.JButton();
        jButtonRen = new javax.swing.JButton();
        jButtonRes = new javax.swing.JButton();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        header1 = new com.raven.component.Header();

        panel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        card1.setColor1(new java.awt.Color(142, 142, 250));
        card1.setColor2(new java.awt.Color(123, 123, 245));
        panel.add(card1);

        card2.setColor1(new java.awt.Color(186, 123, 247));
        card2.setColor2(new java.awt.Color(167, 94, 236));
        panel.add(card2);

        card3.setColor1(new java.awt.Color(241, 208, 62));
        card3.setColor2(new java.awt.Color(211, 184, 61));
        panel.add(card3);

        jButtonMod.setBackground(new java.awt.Color(0, 0, 255));
        jButtonMod.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonMod.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMod.setText("Modifier");
        jButtonMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonSupp.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSupp.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonSupp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupp.setText("Supprimer");
        jButtonSupp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppActionPerformed(evt);
            }
        });

        jButtonRen.setBackground(new java.awt.Color(0, 204, 0));
        jButtonRen.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonRen.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRen.setText("Renouveler Abonnnement");
        jButtonRen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonRen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenActionPerformed(evt);
            }
        });

        jButtonRes.setBackground(new java.awt.Color(255, 204, 51));
        jButtonRes.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButtonRes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRes.setText("ResilierAbonnnement");
        jButtonRes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel.add(jPanel1);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Liste des Abonnés");

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Date inscription", "Num Telph", "Statut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(966, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 368, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel))
                    .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            String nom = (String) table.getValueAt(selectedRow, 0);
            String prenom = (String) table.getValueAt(selectedRow, 1);
            String numeroTelephone = (String) table.getValueAt(selectedRow, 3);
            StatusType statut = (StatusType) table.getValueAt(selectedRow, 4);

            // Convertir le statut en String ("OUI" ou "NON")
            String statutString = (statut == StatusType.OUI) ? "OUI" : "NON";

            // Ouvrir le panel de modification avec les données de l'abonné sélectionné
            ModifAbonne modifAbonne = new ModifAbonne(nom, prenom, numeroTelephone, statutString);
            //System.out.println(modifAbonne);

            // Créer un JDialog pour afficher ModifAbonne
            JDialog dialog = new JDialog();
            dialog.setTitle("Modifier Abonné");
            dialog.setModal(true); // Rend la fenêtre modale
            dialog.setContentPane(modifAbonne); // Ajouter ModifAbonne au JDialog
            dialog.pack(); // Ajuster la taille du JDialog au contenu
            dialog.setLocationRelativeTo(null); // Centrer la fenêtre sur l'écran
            dialog.setVisible(true); // Afficher la fenêtre
            // Rafraîchir le tableau après la fermeture du JDialog
            refreshTable();
            dialog.dispose();
          
        }
        else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonné à modifier.", "Aucun abonné sélectionné", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            String numeroTelephone = (String) table.getValueAt(selectedRow, 3);
            boolean isDeleted = supprimerAbonne(numeroTelephone);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Abonné supprimé avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                // Rafraîchir le tableau après la suppression
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression de l'abonné.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonné à supprimer.", "Aucun abonné sélectionné", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButtonSuppActionPerformed

    private void jButtonRenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            String numeroTelephone = (String) table.getValueAt(selectedRow, 3);
            boolean isRenewed = renouvelerAbonnement(numeroTelephone);
            if (isRenewed) {
                JOptionPane.showMessageDialog(this, "Abonnement renouvelé avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                // Rafraîchir le tableau après le renouvellement
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors du renouvellement de l'abonnement.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonné à renouveler.", "Aucun abonné sélectionné", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonRenActionPerformed

    private void jButtonResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            String numeroTelephone = (String) table.getValueAt(selectedRow, 3);
            boolean isResilied = resilierAbonnement(numeroTelephone);
            if (isResilied) {
                JOptionPane.showMessageDialog(this, "Abonnement résilié avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                // Rafraîchir le tableau après la résiliation
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la résiliation de l'abonnement.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un abonné à résilier.", "Aucun abonné sélectionné", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonResActionPerformed

    // Méthode pour rafraîchir le tableau après une opération
    private void refreshTable() {
    List<Object[]> abonnes = Affichage.getAbonnes();
    table.setRowCount(0); // Vider le tableau
    for (Object[] abonne : abonnes) {
        table.addRow(abonne);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Card card1;
    private com.raven.component.Card card2;
    private com.raven.component.Card card3;
    private com.raven.component.Header header1;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonRen;
    private javax.swing.JButton jButtonRes;
    private javax.swing.JButton jButtonSupp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane panel;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
